
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author root
 */
public class salesperson extends javax.swing.JFrame {

    /**
     * Creates new form salesperson
     */
    static String value;
    public salesperson() {
        initComponents();
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        opass.setVisible(false);
        npass.setVisible(false);
        renpass.setVisible(false);
        passwordconfirm.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        chome.setVisible(false);
        csearch.setVisible(false);
        creport.setVisible(false);
        cconfiguration.setVisible(false);
        confirmbackground.setVisible(false);
        
    }
    public salesperson(String para){
        onlineperson.setText(para);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        onlineperson = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bhome = new javax.swing.JButton();
        bsearch = new javax.swing.JButton();
        bconfiguration = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        breport = new javax.swing.JButton();
        parentpanel = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        printbill = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        tcost = new javax.swing.JTextField();
        received = new javax.swing.JTextField();
        returned = new javax.swing.JTextField();
        generatebill = new javax.swing.JButton();
        nextitem = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        psearch = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        preports = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pconfiguration = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        opass = new javax.swing.JTextField();
        npass = new javax.swing.JTextField();
        renpass = new javax.swing.JTextField();
        passwordconfirm = new javax.swing.JButton();
        changebackground = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chome = new javax.swing.JComboBox();
        csearch = new javax.swing.JComboBox();
        creport = new javax.swing.JComboBox();
        cconfiguration = new javax.swing.JComboBox();
        confirmbackground = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1340, 691));

        jPanel1.setBackground(new java.awt.Color(137, 149, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("                My Department Store");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/salesperson.png")); // NOI18N
        jLabel2.setText("Sales");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/dot.png")); // NOI18N
        jLabel9.setText("Online");

        onlineperson.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        onlineperson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineperson, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(onlineperson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(99, 62, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        bhome.setBackground(new java.awt.Color(191, 158, 245));
        bhome.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bhome.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/homepage.png")); // NOI18N
        bhome.setText("Home");
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        bsearch.setBackground(new java.awt.Color(152, 145, 175));
        bsearch.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bsearch.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/search.png")); // NOI18N
        bsearch.setText("Search");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });

        bconfiguration.setBackground(new java.awt.Color(142, 175, 236));
        bconfiguration.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bconfiguration.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/configuration.png")); // NOI18N
        bconfiguration.setText("Configuration");
        bconfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconfigurationActionPerformed(evt);
            }
        });

        blogout.setBackground(new java.awt.Color(209, 237, 132));
        blogout.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        blogout.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/logout.png")); // NOI18N
        blogout.setText("Log out");
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        breport.setBackground(new java.awt.Color(226, 133, 167));
        breport.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        breport.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/reports.png")); // NOI18N
        breport.setText("Daily Reports");
        breport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bconfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(breport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breport, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        parentpanel.setLayout(new java.awt.CardLayout());

        phome.setBackground(new java.awt.Color(191, 158, 245));

        bill.setColumns(20);
        bill.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        printbill.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        printbill.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/print.png")); // NOI18N
        printbill.setText("Print");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Item Name");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setText("Rate");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Total Cost");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setText("Received");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel8.setText("Returned");

        received.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                receivedKeyPressed(evt);
            }
        });

        generatebill.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        generatebill.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/generatebill.png")); // NOI18N
        generatebill.setText("Generate Bill");
        generatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillActionPerformed(evt);
            }
        });

        nextitem.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        nextitem.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/next.png")); // NOI18N
        nextitem.setText("Next");
        nextitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextitemActionPerformed(evt);
            }
        });

        confirm.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        confirm.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/confirm.png")); // NOI18N
        confirm.setText("Confirm");

        done.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        done.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/checkmark.png")); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity", "Rate", "Total"
            }
        ));
        jScrollPane3.setViewportView(table);

        javax.swing.GroupLayout phomeLayout = new javax.swing.GroupLayout(phome);
        phome.setLayout(phomeLayout);
        phomeLayout.setHorizontalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phomeLayout.createSequentialGroup()
                .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(received, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(phomeLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(returned, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm)
                        .addGap(18, 18, 18)))
                .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addComponent(generatebill)
                        .addGap(117, 117, 117)
                        .addComponent(printbill, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextitem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(199, 199, 199))
        );
        phomeLayout.setVerticalGroup(
            phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phomeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextitem)
                            .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(done))
                        .addGap(18, 18, 18)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(received, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(returned, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(phomeLayout.createSequentialGroup()
                        .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(phomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatebill)
                    .addComponent(confirm)
                    .addComponent(printbill))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        parentpanel.add(phome, "card5");

        psearch.setBackground(new java.awt.Color(152, 145, 175));

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setText("Search By Name");

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/search.png")); // NOI18N
        jButton1.setText("Search");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel11.setText("Search By Code");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Category", "Brand", "Size", "Quantity", "selling Price", "Arrival Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout psearchLayout = new javax.swing.GroupLayout(psearch);
        psearch.setLayout(psearchLayout);
        psearchLayout.setHorizontalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        psearchLayout.setVerticalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psearchLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(psearchLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parentpanel.add(psearch, "card4");

        preports.setBackground(new java.awt.Color(226, 133, 167));

        jButton2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton2.setText(" Today's Report");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaction Id", "Customer Id", "Item Code", "Item Name", "Category", "Brand", "Size", "Quantity", "Rate", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout preportsLayout = new javax.swing.GroupLayout(preports);
        preports.setLayout(preportsLayout);
        preportsLayout.setHorizontalGroup(
            preportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preportsLayout.createSequentialGroup()
                .addContainerGap(658, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(453, 453, 453))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        preportsLayout.setVerticalGroup(
            preportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preportsLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        parentpanel.add(preports, "card3");

        pconfiguration.setBackground(new java.awt.Color(142, 175, 236));

        jButton3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton3.setText("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel12.setText("Old Password");

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel13.setText("New Password");

        jLabel14.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel14.setText("Re New Password");

        passwordconfirm.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        passwordconfirm.setText("Confirm");

        changebackground.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        changebackground.setText("Change Background");
        changebackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebackgroundActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel15.setText("Home");

        jLabel16.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel16.setText("Search");

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel17.setText("Daily Report");

        jLabel18.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel18.setText("Configuration");

        chome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Yellow", "Violet", "Orange", "Grey", "Brown", " " }));

        csearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Yellow", "Violet", "Orange", "Grey", "Brown" }));

        creport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Yellow", "Violet", "Orange", "Grey", "Brown" }));

        cconfiguration.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green", "Blue", "Yellow", "Violet", "Orange", "Grey", "Brown" }));

        confirmbackground.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        confirmbackground.setText("Confirm");
        confirmbackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbackgroundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pconfigurationLayout = new javax.swing.GroupLayout(pconfiguration);
        pconfiguration.setLayout(pconfigurationLayout);
        pconfigurationLayout.setHorizontalGroup(
            pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pconfigurationLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changebackground, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(77, 77, 77)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renpass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cconfiguration, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creport, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(csearch, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chome, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE))
                    .addComponent(npass, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmbackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordconfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        pconfigurationLayout.setVerticalGroup(
            pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pconfigurationLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pconfigurationLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordconfirm)))
                    .addGroup(pconfigurationLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pconfigurationLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changebackground)
                            .addComponent(confirmbackground)))
                    .addGroup(pconfigurationLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        parentpanel.add(pconfiguration, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blogoutActionPerformed

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        parentpanel.removeAll();
        parentpanel.add(phome);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bhomeActionPerformed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        parentpanel.removeAll();
        parentpanel.add(psearch);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bsearchActionPerformed

    private void breportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breportActionPerformed
        parentpanel.removeAll();
        parentpanel.add(preports);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_breportActionPerformed

    private void bconfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconfigurationActionPerformed
        parentpanel.removeAll();
        parentpanel.add(pconfiguration);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bconfigurationActionPerformed

    private void nextitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextitemActionPerformed
        int t=Integer.parseInt(quantity.getText())*Integer.parseInt(rate.getText());
        String total=Integer.toString(t);//converting integer t into string
        String transaction[]={itemname.getText(),quantity.getText(),rate.getText(),total};
        //System.out.println(transaction[0]);
        //System.out.println("length is"+transaction.length);
        DefaultTableModel model= (DefaultTableModel)table.getModel();
        model.addRow(transaction);
        itemname.setText("");
        quantity.setText("");
        rate.setText("");
        itemname.requestFocus();
    }//GEN-LAST:event_nextitemActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        int rowcount=table.getRowCount();//counts the number of row in table
        int sum=0;
        for(int i=0;i<rowcount;i++){
            int t=Integer.parseInt(table.getValueAt(i,3).toString());
            System.out.println(t);
            sum=sum+t;    
        }
        tcost.setText(String.valueOf(sum));
        received.requestFocus();
    }//GEN-LAST:event_doneActionPerformed

    private void receivedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receivedKeyPressed
        int key=evt.getKeyCode();
        if(key==10){
            int t=Integer.parseInt(tcost.getText());
            int r=Integer.parseInt(received.getText());
            System.out.println(r);
            if(r<t){
                JOptionPane.showMessageDialog(null,"Received amount not enterd correctly");
            }
            else{
                returned.setText(String.valueOf(r-t));
            }
        }
    }//GEN-LAST:event_receivedKeyPressed

    private void generatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillActionPerformed
        int i=table.getRowCount();
        int k=table.getColumnCount();
        System.out.println(i);
        System.out.println(k);
        bill.setText("***************************************************\n");
        bill.setText(bill.getText()+"****            My Department Store            ****\n");
        bill.setText(bill.getText()+"***************************************************\n");
        bill.setText(bill.getText()+"** Transaction id :\n");
        bill.setText(bill.getText()+"** Date :\n");
        bill.setText(bill.getText()+"***************************************************\n");
        bill.setText(bill.getText()+"* SN * ItemName       * Quan  * Rate   * Total    *\n");
        bill.setText(bill.getText()+"*'''''''''''''''''''''''''''''''''''''''''''''''''*\n");
        for(int j=0,l=1;j<i;j++,l++){
            bill.setText(bill.getText()+"* "+l+"  ");
            for(int m=0;m<k;m++){
                if(m==0){
                   String a=(table.getModel()).getValueAt(j,m).toString();
                   int len=15-a.length();
                   value=generatespace(a,len);//generate space is the funcion to generate space for bill which is at last
                }
                else if(m==1){
                    String a=(table.getModel()).getValueAt(j,m).toString();
                    int len=6-a.length();
                    value=generatespace(a,len);
                }
                else if(m==2){
                    String a=(table.getModel()).getValueAt(j,m).toString();
                    int len=7-a.length();
                    value=generatespace(a,len);
                }
                else{
                    String a=(table.getModel()).getValueAt(j,m).toString();
                    int len=9-a.length();
                    value=generatespace(a,len);
                }
                bill.setText(bill.getText()+"* "+value);
            }
            bill.setText(bill.getText()+"*\n");
        }
        bill.setText(bill.getText()+"*'''''''''''''''''''''''''''''''''''''''''''''''''*\n");
        String to=tcost.getText();
        int len1=9-to.length();
        String value1=generatespace(to,len1);
        bill.setText(bill.getText()+"*.............................  Total  * "+value1+"*\n");
        String re=received.getText();
        int len2=9-re.length();
        String value2=generatespace(re,len2);
        bill.setText(bill.getText()+"*............................ Received * "+value2+"*\n");
        String ret=returned.getText();
        int len3=9-ret.length();
        String value3=generatespace(ret,len3);
        bill.setText(bill.getText()+"*............................ Returned * "+value3+"*\n");
        bill.setText(bill.getText()+"\n");
        bill.setText(bill.getText()+"*** Thank You For Your Purchase !! Visit Again! ***\n");
        bill.setText(bill.getText()+"***************************************************\n");
        
        tcost.setText("");
        returned.setText("");
        received.setText("");
        DefaultTableModel model= (DefaultTableModel)table.getModel();
        model.setRowCount(0);
        
    }//GEN-LAST:event_generatebillActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel12.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        opass.setVisible(true);
        npass.setVisible(true);
        renpass.setVisible(true);
        passwordconfirm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void changebackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebackgroundActionPerformed
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        chome.setVisible(true);
        csearch.setVisible(true);
        creport.setVisible(true);
        cconfiguration.setVisible(true);
        confirmbackground.setVisible(true);
        
    }//GEN-LAST:event_changebackgroundActionPerformed

    private void confirmbackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbackgroundActionPerformed
       
    }//GEN-LAST:event_confirmbackgroundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesperson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesperson().setVisible(true);
            }
        });
        
    }
    //function to generate space for bill
    public static String generatespace(String a,int b){
        String c=" ";
        for(int i=1;i<b;i++){
            c=c+" ";
        }
        String d=a+c;
        return d;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconfiguration;
    private javax.swing.JButton bhome;
    private javax.swing.JTextArea bill;
    private javax.swing.JButton blogout;
    private javax.swing.JButton breport;
    private javax.swing.JButton bsearch;
    private javax.swing.JComboBox cconfiguration;
    private javax.swing.JButton changebackground;
    private javax.swing.JComboBox chome;
    private javax.swing.JButton confirm;
    private javax.swing.JButton confirmbackground;
    private javax.swing.JComboBox creport;
    private javax.swing.JComboBox csearch;
    private javax.swing.JButton done;
    private javax.swing.JButton generatebill;
    private javax.swing.JTextField itemname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton nextitem;
    private javax.swing.JTextField npass;
    public static javax.swing.JLabel onlineperson;
    private javax.swing.JTextField opass;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JButton passwordconfirm;
    private javax.swing.JPanel pconfiguration;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel preports;
    private javax.swing.JButton printbill;
    private javax.swing.JPanel psearch;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField received;
    private javax.swing.JTextField renpass;
    private javax.swing.JTextField returned;
    private javax.swing.JTable table;
    private javax.swing.JTextField tcost;
    // End of variables declaration//GEN-END:variables
}
