
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author root
 */
public class store extends javax.swing.JFrame {

    /**
     * Creates new form store
     */
    public static Date d;
    public static java.sql.Date da;
    public store() {
        initComponents();
        showDate();
        rmale.setVisible(false);
        rfemale.setVisible(false);
        rchild.setVisible(false);
    }
    
    void showDate() {
        d = new Date();
        SimpleDateFormat a = new SimpleDateFormat("yyyy-MM-dd");
        dates.setText(a.format(d));
        
        da=new java.sql.Date(d.getTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dates = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        badd = new javax.swing.JButton();
        bremove = new javax.swing.JButton();
        bstore = new javax.swing.JButton();
        bsearch = new javax.swing.JButton();
        bconfiguration = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        parentpanel = new javax.swing.JPanel();
        padd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        category = new javax.swing.JComboBox();
        pquantity = new javax.swing.JTextField();
        pbrand = new javax.swing.JTextField();
        psize = new javax.swing.JTextField();
        pcp = new javax.swing.JTextField();
        psp = new javax.swing.JTextField();
        pedate = new datechooser.beans.DateChooserCombo();
        psupplier = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        rmale = new javax.swing.JRadioButton();
        rfemale = new javax.swing.JRadioButton();
        rchild = new javax.swing.JRadioButton();
        pupdate = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        updatesearch = new javax.swing.JTextField();
        updatesearchbutton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        usname = new javax.swing.JTextField();
        uscategory = new javax.swing.JTextField();
        usbrand = new javax.swing.JTextField();
        ussize = new javax.swing.JTextField();
        usgender = new javax.swing.JTextField();
        usquantity = new javax.swing.JTextField();
        uscost = new javax.swing.JTextField();
        usselling = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        usedate = new javax.swing.JTextField();
        updatequantity = new javax.swing.JTextField();
        updatecost = new javax.swing.JTextField();
        updateselling = new javax.swing.JTextField();
        updateedate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pconfiguration = new javax.swing.JPanel();
        premove = new javax.swing.JPanel();
        pstore = new javax.swing.JPanel();
        psearch = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        searchname = new javax.swing.JTextField();
        searchbyname = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        searchcode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(139, 96, 96));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setText("                                      My Department Store");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/store.png")); // NOI18N
        jLabel2.setText("Store");

        dates.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        badd.setBackground(new java.awt.Color(230, 176, 106));
        badd.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        badd.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/additem.png")); // NOI18N
        badd.setText("Add Item");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bremove.setBackground(new java.awt.Color(174, 219, 229));
        bremove.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bremove.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/removeitem.png")); // NOI18N
        bremove.setText("Remove Item");
        bremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bremoveActionPerformed(evt);
            }
        });

        bstore.setBackground(new java.awt.Color(90, 120, 134));
        bstore.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bstore.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/store.png")); // NOI18N
        bstore.setText("Store");
        bstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstoreActionPerformed(evt);
            }
        });

        bsearch.setBackground(new java.awt.Color(177, 167, 121));
        bsearch.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bsearch.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/search.png")); // NOI18N
        bsearch.setText("Search");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });

        bconfiguration.setBackground(new java.awt.Color(102, 98, 111));
        bconfiguration.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        bconfiguration.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/configuration.png")); // NOI18N
        bconfiguration.setText("Configuration");
        bconfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconfigurationActionPerformed(evt);
            }
        });

        blogout.setBackground(new java.awt.Color(171, 119, 168));
        blogout.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        blogout.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/logout.png")); // NOI18N
        blogout.setText("Log out");

        jButton2.setBackground(new java.awt.Color(167, 143, 135));
        jButton2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/update.png")); // NOI18N
        jButton2.setText("Update Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(badd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bstore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bconfiguration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bremove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(badd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bremove, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bstore, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bconfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        parentpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        parentpanel.setLayout(new java.awt.CardLayout());

        padd.setBackground(new java.awt.Color(230, 176, 106));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Item Name");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("Category");

        Quantity.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        Quantity.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setText("Brand");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Size");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setText("Cost Price");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel8.setText("Selling Price");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel9.setText("Expiry Date");

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel10.setText("Supplier");

        pname.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sports", "Electric", "Clothes", "Drinks", "Food" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        pquantity.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        pbrand.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        psize.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        pcp.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        psp.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        pedate.setCalendarPreferredSize(new java.awt.Dimension(350, 350));
        pedate.setFieldFont(new java.awt.Font("Cantarell", java.awt.Font.PLAIN, 11));

        psupplier.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        add.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        add.setText("Submit");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        buttonGroup1.add(rmale);
        rmale.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        rmale.setText("M");

        buttonGroup1.add(rfemale);
        rfemale.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        rfemale.setText("F");

        buttonGroup1.add(rchild);
        rchild.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        rchild.setText("C");

        javax.swing.GroupLayout paddLayout = new javax.swing.GroupLayout(padd);
        padd.setLayout(paddLayout);
        paddLayout.setHorizontalGroup(
            paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paddLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pname)
                        .addComponent(pquantity)
                        .addComponent(pbrand)
                        .addComponent(psize)
                        .addComponent(pcp)
                        .addComponent(psp)
                        .addComponent(pedate, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(psupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paddLayout.createSequentialGroup()
                        .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rmale)
                        .addGap(18, 18, 18)
                        .addComponent(rfemale)
                        .addGap(18, 18, 18)
                        .addComponent(rchild)))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        paddLayout.setVerticalGroup(
            paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paddLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rmale)
                        .addComponent(rfemale)
                        .addComponent(rchild)))
                .addGap(18, 18, 18)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paddLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psp, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(paddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paddLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paddLayout.createSequentialGroup()
                        .addComponent(pedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(psupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        parentpanel.add(padd, "card2");

        pupdate.setBackground(new java.awt.Color(167, 143, 135));

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setText("Enter Item Code");

        updatesearchbutton.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        updatesearchbutton.setIcon(new javax.swing.ImageIcon("/root/Documents/notes and projects/icons for project/search.png")); // NOI18N
        updatesearchbutton.setText("Search");
        updatesearchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesearchbuttonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel14.setText("Name");

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel15.setText("Category");

        jLabel16.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel16.setText("Brand");

        jLabel17.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel17.setText("Size");

        jLabel18.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel18.setText("Gender");

        jLabel19.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel19.setText("Quantity");

        jLabel20.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel20.setText("Cost Price");

        jLabel21.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel21.setText("Selling Price");

        usname.setEditable(false);

        uscategory.setEditable(false);

        usbrand.setEditable(false);

        ussize.setEditable(false);

        usgender.setEditable(false);

        usquantity.setEditable(false);

        uscost.setEditable(false);

        usselling.setEditable(false);

        jLabel22.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel22.setText("Expiry Date");

        usedate.setEditable(false);

        updatequantity.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N

        updatecost.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        updatecost.setName(""); // NOI18N

        updateselling.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N

        updateedate.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N

        jButton3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton3.setText("Update");

        javax.swing.GroupLayout pupdateLayout = new javax.swing.GroupLayout(pupdate);
        pupdate.setLayout(pupdateLayout);
        pupdateLayout.setHorizontalGroup(
            pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pupdateLayout.createSequentialGroup()
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pupdateLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(updatesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(updatesearchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pupdateLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usname)
                            .addComponent(uscategory)
                            .addComponent(usbrand)
                            .addComponent(ussize)
                            .addComponent(usgender)
                            .addComponent(usquantity)
                            .addComponent(uscost)
                            .addComponent(usselling)
                            .addComponent(usedate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pupdateLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pupdateLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatequantity)
                                    .addComponent(updatecost)
                                    .addComponent(updateselling)
                                    .addComponent(updateedate, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        pupdateLayout.setVerticalGroup(
            pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pupdateLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatesearchbutton))
                .addGap(57, 57, 57)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uscategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ussize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pupdateLayout.createSequentialGroup()
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pupdateLayout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatequantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pupdateLayout.createSequentialGroup()
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uscost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updatecost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateselling, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pupdateLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateedate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        parentpanel.add(pupdate, "card7");

        pconfiguration.setBackground(new java.awt.Color(102, 98, 111));

        javax.swing.GroupLayout pconfigurationLayout = new javax.swing.GroupLayout(pconfiguration);
        pconfiguration.setLayout(pconfigurationLayout);
        pconfigurationLayout.setHorizontalGroup(
            pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1219, Short.MAX_VALUE)
        );
        pconfigurationLayout.setVerticalGroup(
            pconfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        parentpanel.add(pconfiguration, "card6");

        premove.setBackground(new java.awt.Color(174, 219, 229));

        javax.swing.GroupLayout premoveLayout = new javax.swing.GroupLayout(premove);
        premove.setLayout(premoveLayout);
        premoveLayout.setHorizontalGroup(
            premoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1219, Short.MAX_VALUE)
        );
        premoveLayout.setVerticalGroup(
            premoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        parentpanel.add(premove, "card5");

        pstore.setBackground(new java.awt.Color(90, 120, 134));

        javax.swing.GroupLayout pstoreLayout = new javax.swing.GroupLayout(pstore);
        pstore.setLayout(pstoreLayout);
        pstoreLayout.setHorizontalGroup(
            pstoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1219, Short.MAX_VALUE)
        );
        pstoreLayout.setVerticalGroup(
            pstoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        parentpanel.add(pstore, "card4");

        psearch.setBackground(new java.awt.Color(177, 167, 121));

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setText("Name");

        searchbyname.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        searchbyname.setText("Search By Name");

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel12.setText("Code");

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setText("Search By Code");

        javax.swing.GroupLayout psearchLayout = new javax.swing.GroupLayout(psearch);
        psearch.setLayout(psearchLayout);
        psearchLayout.setHorizontalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(psearchLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(searchname, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(psearchLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        psearchLayout.setVerticalGroup(
            psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psearchLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbyname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(psearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(468, Short.MAX_VALUE))
        );

        parentpanel.add(psearch, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        parentpanel.removeAll();
        parentpanel.add(padd);
        parentpanel.repaint();
        parentpanel.revalidate();
        
    }//GEN-LAST:event_baddActionPerformed

    private void bremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bremoveActionPerformed
        parentpanel.removeAll();
        parentpanel.add(premove);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bremoveActionPerformed

    private void bstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstoreActionPerformed
        parentpanel.removeAll();
        parentpanel.add(pstore);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bstoreActionPerformed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        parentpanel.removeAll();
        parentpanel.add(psearch);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bsearchActionPerformed

    private void bconfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconfigurationActionPerformed
        parentpanel.removeAll();
        parentpanel.add(pconfiguration);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_bconfigurationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        parentpanel.removeAll();
        parentpanel.add(pupdate);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (pname.getText().trim().isEmpty() || pquantity.getText().trim().isEmpty() || psize.getText().trim().isEmpty() || pcp.getText().trim().isEmpty() || psp.getText().trim().isEmpty() || psupplier.getText().trim().isEmpty() || pbrand.getText().trim().isEmpty() || pedate.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "one or more textfield is empty");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                
                Connection conn = null;
                conn=DriverManager.getConnection("jdbc:sqlserver://192.168.100.132:1433;databaseName=OurDepartment;username=sa;password=dipeshkoirala");
                System.out.println("Connected to database");
                String pcategory = (String) category.getSelectedItem();
                if(pcategory.equals("Clothes")){
                    String sql="insert into storetable(Product_Name,Category,Brand,Size,Gender,Quantity,CP,SP,Arrival_Date,Expiry_Date,Supplier) values(?,?,?,?,?,?,?,?,?,?,?)";
                    String name = pname.getText();
                    String q = pquantity.getText();
                    int quantity = Integer.parseInt(q);
                    String size = psize.getText();
                    int sizes = Integer.parseInt(size);
                    String cp = pcp.getText();
                    int cost = Integer.parseInt(cp);
                    String sp = psp.getText();
                    int selling = Integer.parseInt(sp);
                    String supplier = psupplier.getText();
                    String brand=pbrand.getText();
                    String edate=pedate.getText();
                    String clothtype=buttonGroup1.getSelection().getActionCommand();
                
                    PreparedStatement psmt = conn.prepareStatement(sql);
                    psmt.setString(1, name);
                    psmt.setString(2, pcategory);
                    psmt.setString(3, brand);
                    psmt.setInt(4, sizes);
                    psmt.setString(5, clothtype);
                    psmt.setInt(6, quantity);
                    psmt.setInt(7, cost);
                    psmt.setInt(8, selling);
                    psmt.setDate(9,da);
                    psmt.setString(10, edate);
                    psmt.setString(11,supplier);
                
                    psmt.execute();
                }
                else{
                    String sql="insert into storetable(Product_Name,Category,Brand,Size,Quantity,CP,SP,Arrival_Date,Expiry_Date,Supplier) values(?,?,?,?,?,?,?,?,?,?)";
                    
                    String name = pname.getText();
                    String q = pquantity.getText();
                    int quantity = Integer.parseInt(q);
                    String size = psize.getText();
                    int sizes = Integer.parseInt(size);
                    String cp = pcp.getText();
                    int cost = Integer.parseInt(cp);
                    String sp = psp.getText();
                    int selling = Integer.parseInt(sp);
                    String supplier = psupplier.getText();
                    String brand=pbrand.getText();
                    String edate=pedate.getText();
                    
                    
                
                    PreparedStatement psmt = conn.prepareStatement(sql);
                    psmt.setString(1, name);
                    psmt.setString(2, pcategory);
                    psmt.setString(3, brand);
                    psmt.setInt(4, sizes);
                    psmt.setInt(5, quantity);
                    psmt.setInt(6, cost);
                    psmt.setInt(7, selling);
                    psmt.setDate(8,da);
                    psmt.setString(9, edate);
                    psmt.setString(10, supplier);
                    
                
                    psmt.execute();
                }
                
                

            } catch (Exception e) {
                System.out.println(e);
            }
            int i = JOptionPane.showConfirmDialog(null, "Item added sucessfully", "Added", JOptionPane.OK_CANCEL_OPTION);
            if (i == JOptionPane.OK_OPTION) {
                pcp.setText("");
                pname.setText("");
                psp.setText("");
                pquantity.setText("");
                psize.setText("");
                psupplier.setText("");
                pbrand.setText("");
                pedate.setText("");
                rmale.setVisible(false);
                rfemale.setVisible(false);
                rchild.setVisible(false);
            }
        }

    }//GEN-LAST:event_addActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        String d=(String)category.getSelectedItem();
        if(d.equals("Clothes")){
            rmale.setActionCommand("male");
            rfemale.setActionCommand("female");
            rchild.setActionCommand("children");
            rmale.setVisible(true);
            rfemale.setVisible(true);
            rchild.setVisible(true);
        }
    }//GEN-LAST:event_categoryActionPerformed

    private void updatesearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesearchbuttonActionPerformed
        String usearch=updatesearch.getText();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://192.168.100.132:1433;databaseName=OurDepartment;username=sa;password=dipeshkoirala");
            String sql="select Product_Name,Category,Brand,Size,Gender,Quantity,CP,SP,Expiry_Date from storetable where Product_Id=?";
            PreparedStatement psmt=con.prepareStatement(sql);
            psmt.setString(1, usearch);
            ResultSet rs=psmt.executeQuery();
            while(rs.next()){
                String name=rs.getString("Product_Name");
                String category=rs.getString("Category");
                String brand=rs.getString("Brand");
                String size=rs.getString("Size");
                String gender=rs.getString("Gender");
                int quantity=rs.getInt("Quantity");
                float cp=rs.getFloat("CP");
                float sp=rs.getFloat("SP");
                Date date=rs.getDate("Expiry_Date");
                
                usname.setText(name);
                uscategory.setText(category);
                usbrand.setText(brand);
                ussize.setText(size);
                usgender.setText(gender);
                usquantity.setText(String.valueOf(quantity));
                uscost.setText(String.valueOf(cp));
                usselling.setText(String.valueOf(sp));
                usedate.setText(String.valueOf(date));
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_updatesearchbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton add;
    private javax.swing.JButton badd;
    private javax.swing.JButton bconfiguration;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bremove;
    private javax.swing.JButton bsearch;
    private javax.swing.JButton bstore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox category;
    private javax.swing.JLabel dates;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel padd;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JTextField pbrand;
    private javax.swing.JPanel pconfiguration;
    private javax.swing.JTextField pcp;
    private datechooser.beans.DateChooserCombo pedate;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pquantity;
    private javax.swing.JPanel premove;
    private javax.swing.JPanel psearch;
    private javax.swing.JTextField psize;
    private javax.swing.JTextField psp;
    private javax.swing.JPanel pstore;
    private javax.swing.JTextField psupplier;
    private javax.swing.JPanel pupdate;
    private javax.swing.JRadioButton rchild;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JButton searchbyname;
    private javax.swing.JTextField searchcode;
    private javax.swing.JTextField searchname;
    private javax.swing.JTextField updatecost;
    private javax.swing.JTextField updateedate;
    private javax.swing.JTextField updatequantity;
    private javax.swing.JTextField updatesearch;
    private javax.swing.JButton updatesearchbutton;
    private javax.swing.JTextField updateselling;
    private javax.swing.JTextField usbrand;
    private javax.swing.JTextField uscategory;
    private javax.swing.JTextField uscost;
    private javax.swing.JTextField usedate;
    private javax.swing.JTextField usgender;
    private javax.swing.JTextField usname;
    private javax.swing.JTextField usquantity;
    private javax.swing.JTextField usselling;
    private javax.swing.JTextField ussize;
    // End of variables declaration//GEN-END:variables
}
